install:
  - sudo apt-get install -y linux-image-virtual kernel linux-image-extra-virtual
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose
script:
  - docker-compose -f ~/Development/papusa/docker-compose.test.yml -p ci build
  - docker-compose -f ~/Development/papusa/docker-compose.test.yml -p ci up -d
  - if [ "$(docker logs --tail 1 ci_test_1)" != "Tests passed!" ]; then exit 1; fi
notifications:
  email:
    - dev@karimtabet.com
