sudo: required
services:
  - docker
env:
  COMPOSE_VERSION: 1.11.2
before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
script:
  - make test
notifications:
  email:
   - dev@karimtabet.com
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      ./release.sh
    fi
  