############################################################
# Dockerfile to test a pre-built Papusa project
# Based on an Ubuntu Image
# Calls etest.sh
############################################################

FROM ubuntu:16.04

RUN apt-get update && apt-get install -yq curl && apt-get clean

WORKDIR /app

ADD test.sh /app/test.sh

CMD ["bash", "test.sh"]
