version: '2.1'  
services:

  nginx:
    image: nginx:latest
    container_name: papusa_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    volumes_from:
      - web
    depends_on:
      - web

  web:
    build: .
    image: karimtabet/papusa
    container_name: papusa_web
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - "postgres:db"
    expose:
      - "8000"
    volumes:
      - /srv/logs
      - /srv/papusa
    environment:
      - SECRET_KEY='stagingkey'
      - DB_URL=postgres://papusa:papusa@db:5432/papusa
      - REDIS_URL=redis://redis:6379/1

  postgres:
    image: postgres:latest
    container_name: papusa_db
    environment:
      - POSTGRES_USER=papusa
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:latest
    container_name: papusa_redis
