version: '2'  
services:  
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
 
  web:
    build: .
    depends_on:
      - db
    expose:
      - "8000"

  db:
    image: postgres:latest

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    links:
      - web
