version: '2'  
services:

  nginx:
    image: nginx:latest
    container_name: papusa_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: papusa_web
    depends_on:
      - postgres
      - redis
    links:
      - "postgres:db"
    expose:
      - "8000"
    environment:
      - SECRET_KEY='stagingkey'
      - DB_URL=postgres://papusa:papusa@db:5432/papusa

  postgres:
    image: postgres:latest
    container_name: papusa_db
    environment:
      - POSTGRES_USER=papusa

  redis:
    image: redis:latest
    container_name: papusa_redis