# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtaildocs', '0007_merge'),
        ('app', '0004_homepage_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePagePromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('fa_icon', models.CharField(blank=True, help_text='Copy the name of any icon from fontawesome.io/icons/', max_length=30, verbose_name='Font Awesome Icon')),
                ('header', models.CharField(max_length=24)),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='logo',
        ),
        migrations.AddField(
            model_name='homepagepromotion',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='app.HomePage'),
        ),
        migrations.AddField(
            model_name='homepagepromotion',
            name='promotion_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_pages', to='wagtailcore.Page'),
        ),
    ]
