# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('app', '0006_auto_20170717_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageFooterPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('header', models.CharField(max_length=24)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_promotions', to='app.HomePage')),
                ('promotion_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_promotion_pages', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='homepagepromotion',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='homepagepromotion',
            name='fa_icon',
        ),
        migrations.RemoveField(
            model_name='homepagepromotion',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='homepagepromotion',
            name='link_external',
        ),
        migrations.RemoveField(
            model_name='homepagepromotion',
            name='link_page',
        ),
    ]
