# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('app', '0008_auto_20170811_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_text',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
