# Generated by Django 2.0.6 on 2018-06-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180429_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.DeleteModel(
            name='HomePageCarouselItem',
        ),
    ]
